/* 견적 */
DROP TABLE Estimate; 

/* 산출 */
DROP TABLE Calculate ;

/* 카운트 */
DROP TABLE Count ;

/* 테마 */
DROP TABLE THEME ;

/* 포스트 */
DROP TABLE POST ;

/* 포스트 댓글 */
DROP TABLE POST_COMMENT	;	 

/* 유저 팔로우 */
DROP TABLE USER_FOLLOW ;

/* 테마 팔로우 */
DROP TABLE THEME_FOLLOW ;

/* 회원 */
DROP TABLE MEMBER ;

/* 신고사항 게시판 */
DROP TABLE REPORT ;

/* 문의 게시판 */
DROP TABLE INQUIRY ;

/* 공지사항 */
DROP TABLE NOTICE ;

/* 마이투어데이터 */
DROP TABLE MYTOURDATA ;

/* 마이투어북 */
DROP TABLE MYTOURBOOK ;

/* 상품 */
DROP TABLE products;

/* 결제 */
DROP TABLE payments ;

/* 견적 */
CREATE TABLE Estimate (
	OFFERCODE NUMBER NOT NULL, /* 오퍼코드 */
	AREACODE NUMBER, /* 지역코드 */
	SIGUNGUCODE NUMBER, /* 시군구코드 */
	TITLE VARCHAR(255), /* 제목 */
	CONTENT VARCHAR(255), /* 내용 */
	NUMOFATTR NUMBER, /* 관광지개수 */
	USERID VARCHAR2(20) /* 작성자ID */
);

ALTER TABLE Estimate
	ADD
		CONSTRAINT PK_Estimate
		PRIMARY KEY (
			OFFERCODE
		);

/* 산출 */
CREATE TABLE Calculate (
	RESULTCODE NUMBER NOT NULL, /* 산출코드 */
	OFFERCODE NUMBER, /* 오퍼코드 */
	ROUTE VARCHAR(255), /* 경로 */
	TITLE VARCHAR(255), /* 제목 */
	CONTENT VARCHAR(255), /* 내용 */
	VIEWCNT NUMBER, /* 조회수 */
	USERID VARCHAR2(20) /* 산출자ID */
);

ALTER TABLE Calculate
	ADD
		CONSTRAINT PK_Calculate
		PRIMARY KEY (
			RESULTCODE
		);

/* 카운트 */
CREATE TABLE Count (
	AREACODE NUMBER, /* 지역코드 */
	SIGUNGUCODE NUMBER, /* 시군구코드 */
	CONTENTID NUMBER, /* 관광지번호 */
	MYTOURCNT NUMBER, /* 마이투어추가수 */
	VIEWCNT NUMBER, /* 조회수 */
	LIKECNT NUMBER /* 좋아요수 */
);

/* 테마 */
CREATE TABLE THEME (
	THEME_ID NUMBER NOT NULL, /* 테마 ID */
	THEME_NAME VARCHAR2(50) NOT NULL /* 테마 이름 */
);

ALTER TABLE THEME
	ADD
		CONSTRAINT PK_THEME
		PRIMARY KEY (
			THEME_ID
		);

/* 포스트 */
CREATE TABLE POST (
	POST_ID NUMBER NOT NULL, /* 포스트 ID */
	POST_TITLE VARCHAR2(40) NOT NULL, /* 포스트 제목 */
	POST_CONTENT VARCHAR2(300) NOT NULL, /* 포스트 내용 */
	POST_IMG_PATH VARCHAR2(500), /* 포스트 이미지 경로 */
	ATTRLOC1 NUMBER, /* 지역코드 */
	ATTRLOC2 NUMBER, /* 시군별코드 */
	POST_THEME_ID NUMBER NOT NULL, /* 포스트 테마 ID */
	POST_DELFLAG CHAR NOT NULL, /* 포스트 삭제여부 */
	POST_REGDATE DATE NOT NULL, /* 포스트 등록일 */
	POST_LIKE_COUNT NUMBER(5) NOT NULL, /* 포스트 좋아요수 */
	POST_VIEW_COUNT NUMBER(5) NOT NULL, /* 포스트 조회수 */
	ID VARCHAR2(20), /* 포스트 작성자 ID */
	BOOKNO NUMBER /* 포스트 투어 ID */
);

ALTER TABLE POST
	ADD
		CONSTRAINT PK_POST
		PRIMARY KEY (
			POST_ID
		);

/* 포스트 댓글 */
CREATE TABLE POST_COMMENT		 (
	COMMENT_ID NUMBER NOT NULL, /* 댓글 ID */
	COMMENT_POST_ID NUMBER NOT NULL, /* 댓글 작성 포스트 ID */
	COMMENT_CONTENT VARCHAR2(300) NOT NULL, /* 댓글 내용 */
	COMMENT_REGDATE DATE NOT NULL, /* 댓글 등록일 */
	COMMENT_DELFLAG CHAR NOT NULL, /* 댓글 삭제여부 */
	ID VARCHAR2(20) /* 댓글 작성자 ID */
);

ALTER TABLE POST_COMMENT		
	ADD
		CONSTRAINT PK_POST_COMMENT		
		PRIMARY KEY (
			COMMENT_ID
		);

/* 유저 팔로우 */
CREATE TABLE USER_FOLLOW (
	USER_FOLLOW_ID NUMBER NOT NULL, /* 번호 */
	FOLLOW_ID VARCHAR2(20), /* 팔로우 유저 ID */
	FOLLOWING_ID VARCHAR2(20) /* 팔로잉 유저 ID */
);

ALTER TABLE USER_FOLLOW
	ADD
		CONSTRAINT PK_USER_FOLLOW
		PRIMARY KEY (
			USER_FOLLOW_ID
		);

/* 테마 팔로우 */
CREATE TABLE THEME_FOLLOW (
	THEME_FOLLOW_ID NUMBER NOT NULL, /* 테마 팔로우 ID */
	THEME_FOLLOWING_ID NUMBER NOT NULL, /* 테마 ID */
	userID VARCHAR2(20) /* 테마 팔로우 유저 ID */
);

ALTER TABLE THEME_FOLLOW
	ADD
		CONSTRAINT PK_THEME_FOLLOW
		PRIMARY KEY (
			THEME_FOLLOW_ID
		);

/* 회원 */
CREATE TABLE MEMBER (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	PASSWORD VARCHAR2(20), /* 비밀번호 */
	NAME VARCHAR2(30), /* 이름 */
	NICKNAME VARCHAR2(30), /* 닉네임 */
	PHONE VARCHAR2(20), /* 전화번호 */
	EMAIL VARCHAR2(40), /* 이메일 */
	JOINDATE DATE, /* 가입일 */
	PROFILE_IMG_PATH VARCHAR2(500), /* 프로필사진 경로 */
	DELFLAG CHAR NOT NULL, /* 탈퇴 여부 */
	MANAGER CHAR, /* 관리자 여부 */
	FINAL_LOGIN DATE, /* 최종 로그인 날짜 */
	PANALTY CHAR, /* 패널티 여부 */
	PANALTY_END_DATE DATE, /* 패널티 기간 */
	DORMANCYFLAG CHAR, /* 휴면 계정예부 */
	SNSJOIN CHAR /* SNS가입 여부 */
);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			ID
		);

/* 신고사항 게시판 */
CREATE TABLE REPORT (
	REPORT_NUM NUMBER NOT NULL, /* 신고 글 번호 */
	TITLE VARCHAR2(40), /* 제목 */
	CONTENT VARCHAR2(300), /* 내용 */
	REFER NUMBER, /* 원글 번호 */
	STEP NUMBER, /* 단계 */
	DEPTH NUMBER, /* 깊이 */
	DELFLAG CHAR NOT NULL, /* 삭제여부 */
	REGDATE DATE, /* 작성일 */
	SECRETFLAG CHAR, /* 비밀글여부 */
	USERID VARCHAR2(20) /* 작성자ID */
);

ALTER TABLE REPORT
	ADD
		CONSTRAINT PK_REPORT
		PRIMARY KEY (
			REPORT_NUM
		);

/* 문의 게시판 */
CREATE TABLE INQUIRY (
	INQUIRY_NUM NUMBER NOT NULL, /* 문의 번호 */
	TITLE VARCHAR2(40), /* 제목 */
	CONTENT VARCHAR2(300), /* 내용 */
	REFER NUMBER, /* 원글 번호 */
	STEP NUMBER, /* 단계 */
	DEPTH NUMBER, /* 깊이 */
	DELFLAG CHAR NOT NULL, /* 삭제여부 */
	REGDATE DATE, /* 작성일 */
	SECRETFLAG CHAR, /* 비밀글여 */
	USERID VARCHAR2(20) /* 작성자ID */
);

ALTER TABLE INQUIRY
	ADD
		CONSTRAINT PK_INQUIRY
		PRIMARY KEY (
			INQUIRY_NUM
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_NUM NUMBER NOT NULL, /* 공지사항 번호 */
	TITLE VARCHAR2(40), /* 제목 */
	CONTENT VARCHAR2(300), /* 내용 */
	DELFLAG CHAR NOT NULL, /* 삭제 여부 */
	REGDATE DATE, /* 작성일 */
	USERID VARCHAR2(20) /* 작성자ID */
);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_NUM
		);

/* 마이투어데이터 */
CREATE TABLE MYTOURDATA (
	DATANO NUMBER NOT NULL, /* 데이터번호 */
	BOOKNO NUMBER, /* 책번호 */
	ATTRLOC1 NUMBER, /* 지역코드 */
	ATTRLOC2 NUMBER, /* 시군별코드 */
	NAME VARCHAR2(100), /* 이름 */
	TOURORDER NUMBER, /* 투어순서 */
	CONTENTID NUMBER /* 관광지코드 */
);

ALTER TABLE MYTOURDATA
	ADD
		CONSTRAINT PK_MYTOURDATA
		PRIMARY KEY (
			DATANO
		);

/* 마이투어북 */
CREATE TABLE MYTOURBOOK (
	BOOKNO NUMBER NOT NULL, /* 책번호 */
	TITLE VARCHAR2(40) NOT NULL, /* 제목 */
	AURTHOR VARCHAR2(25) NOT NULL, /* 저자 */
	REGDATE DATE NOT NULL, /* 등록일 */
	KEYWORD VARCHAR2(50) NOT NULL, /* 키워드 */
	DELFLAG CHAR NOT NULL /* 삭제여부 */
);

ALTER TABLE MYTOURBOOK
	ADD
		CONSTRAINT PK_MYTOURBOOK
		PRIMARY KEY (
			BOOKNO
		);

create sequence BOOKNO_SEQ START WITH 1 INCREMENT BY 1;;
		
/* 상품 */
CREATE TABLE products (
	PRODUCT_CODE NUMBER NOT NULL, /* 상품코드 */
	NAME VARCHAR2(50), /* 상품이름 */
	PRICE NUMBER, /* 금액 */
	DESCRIPTION VARCHAR2(500), /* 설명 */
	REG_DATE DATE, /* 등록일 */
	DELFLAG CHAR, /* 상품삭제여부 */
	UPDATE_DATE DATE /* 업데이트일 */
);

CREATE SEQUENCE PRODUCTS_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE products
	ADD
		CONSTRAINT PK_products
		PRIMARY KEY (
			PRODUCT_CODE
		);

/* 결제 */
CREATE TABLE payments (
	PAYCODE NUMBER NOT NULL, /* 결제코드 */
	IMP_UID VARCHAR2(50), /* 아임포트코드 */
	PG VARCHAR2(30), /* 결제사 */
	PAY_METHOD VARCHAR2(15), /* 결제방법 */
	CARD_NAME VARCHAR2(50),  /* 결제카드사 */
	PAY_STATE VARCHAR2(15), /* 결제상태 */
	PRICE NUMBER, /* 결제금액 */
	PAY_DATE DATE, /* 결제일 */
	CANCELYN CHAR, /* 취소가능여부 */
	CANCEL_DATE DATE, /* 취소일 */
	CANCEL_DESC VARCHAR2(500), /* 취소이유 */
	PRODUCT_CODE NUMBER, /* 상품코드 */
	USERID VARCHAR2(20), /* 회원ID */
	DELFLAG CHAR, /* 결제기록삭제여부 */
	UPDATE_DATE DATE /* 업데이트일 */
);

CREATE SEQUENCE PAYMENTS_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE payments
	ADD
		CONSTRAINT PK_payments
		PRIMARY KEY (
			PAYCODE
		);

ALTER TABLE Estimate
	ADD
		CONSTRAINT FK_MEMBER_TO_Estimate
		FOREIGN KEY (
			USERID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE Calculate
	ADD
		CONSTRAINT FK_Estimate_TO_Calculate
		FOREIGN KEY (
			OFFERCODE
		)
		REFERENCES Estimate (
			OFFERCODE
		);

ALTER TABLE Calculate
	ADD
		CONSTRAINT FK_MEMBER_TO_Calculate
		FOREIGN KEY (
			USERID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE POST
	ADD
		CONSTRAINT FK_THEME_TO_POST
		FOREIGN KEY (
			POST_THEME_ID
		)
		REFERENCES THEME (
			THEME_ID
		);

ALTER TABLE POST
	ADD
		CONSTRAINT FK_MEMBER_TO_POST
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE POST
	ADD
		CONSTRAINT FK_MYTOURBOOK_TO_POST
		FOREIGN KEY (
			BOOKNO
		)
		REFERENCES MYTOURBOOK (
			BOOKNO
		);

ALTER TABLE POST_COMMENT		
	ADD
		CONSTRAINT FK_POST_TO_POST_COMMENT		
		FOREIGN KEY (
			COMMENT_POST_ID
		)
		REFERENCES POST (
			POST_ID
		);

ALTER TABLE POST_COMMENT		
	ADD
		CONSTRAINT FK_MEMBER_TO_POST_COMMENT		
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE USER_FOLLOW
	ADD
		CONSTRAINT FK_MEMBER_TO_USER_FOLLOW
		FOREIGN KEY (
			FOLLOW_ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE USER_FOLLOW
	ADD
		CONSTRAINT FK_MEMBER_TO_USER_FOLLOW2
		FOREIGN KEY (
			FOLLOWING_ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE THEME_FOLLOW
	ADD
		CONSTRAINT FK_THEME_TO_THEME_FOLLOW
		FOREIGN KEY (
			THEME_FOLLOWING_ID
		)
		REFERENCES THEME (
			THEME_ID
		);

ALTER TABLE THEME_FOLLOW
	ADD
		CONSTRAINT FK_MEMBER_TO_THEME_FOLLOW
		FOREIGN KEY (
			userID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE REPORT
	ADD
		CONSTRAINT FK_MEMBER_TO_REPORT
		FOREIGN KEY (
			USERID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE INQUIRY
	ADD
		CONSTRAINT FK_MEMBER_TO_INQUIRY
		FOREIGN KEY (
			USERID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_MEMBER_TO_NOTICE
		FOREIGN KEY (
			USERID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE MYTOURDATA
	ADD
		CONSTRAINT FK_MYTOURBOOK_TO_MYTOURDATA
		FOREIGN KEY (
			BOOKNO
		)
		REFERENCES MYTOURBOOK (
			BOOKNO
		);

ALTER TABLE payments
	ADD
		CONSTRAINT FK_products_TO_payments
		FOREIGN KEY (
			PRODUCT_CODE
		)
		REFERENCES products (
			PRODUCT_CODE
		);

ALTER TABLE payments
	ADD
		CONSTRAINT FK_MEMBER_TO_payments
		FOREIGN KEY (
			USERID
		)
		REFERENCES MEMBER (
			ID
		);
